name: Rust - Linux Test

on: [workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cd bindings/rust && cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
